### ISSUE TITLE
Use random numbers in this range instead of a choice of presets

### ISSUE THREAD

**Issue by KeaganP-dev** [COMP2522/project-dui-infinite#103]
https://github.com/COMP2522/project-dui-infinite/blob/a5410a7d7c770a9f37d387359f150561253d73d8/src/main/java/org/bcit/comp2522/dui/client/EnemyCar.java#L19

**Comment by KeaganP-dev** [comment]
creates more possibility for gameplay

**Comment by erictatchell** [comment]
done, thanks for your feedback?
