### ISSUE TITLE
Remove from UI

### ISSUE THREAD

**Issue by KeaganP-dev** [COMP2522/project-dui-infinite#107]
https://github.com/COMP2522/project-dui-infinite/blob/a5410a7d7c770a9f37d387359f150561253d73d8/src/main/java/org/bcit/comp2522/dui/ui/UI.java#L52

**Comment by KeaganP-dev** [comment]
create EnemyCarManager that can handle these things

**Comment by erictatchell** [comment]
fixed, thanks for the feedback g
