### ISSUE TITLE
Make variables private and make a getter functions for them

### ISSUE THREAD

**Issue by Qct0411** [COMP2522/project-dui-infinite#65]
https://github.com/COMP2522/project-dui-infinite/blob/a5410a7d7c770a9f37d387359f150561253d73d8/src/main/java/org/bcit/comp2522/dui/client/KeyInput.java#L26

https://github.com/COMP2522/project-dui-infinite/blob/a5410a7d7c770a9f37d387359f150561253d73d8/src/main/java/org/bcit/comp2522/dui/client/KeyInput.java#L29

**Comment by erictatchell** [comment]
done, thanks for the feedback!
