### ISSUE TITLE
Refactor this into one method

### ISSUE THREAD

**Issue by cherylau** [COMP2522/project-dui-infinite#67]
https://github.com/COMP2522/project-dui-infinite/blob/a5410a7d7c770a9f37d387359f150561253d73d8/src/main/java/org/bcit/comp2522/dui/ui/UI.java#L52

![image](https://user-images.githubusercontent.com/113461643/229177483-d139e233-8a3d-4871-ae90-e0b404e07d8b.png)

**Comment by erictatchell** [comment]
fixed/refactored. thanks for your feedback!
