### ISSUE TITLE
Consider breaking this class down into a composite of UI elements to increase modularity of the project.

### ISSUE THREAD

**Issue by camwalford** [COMP2522/project-dui-infinite#69]
https://github.com/COMP2522/project-dui-infinite/blob/a5410a7d7c770a9f37d387359f150561253d73d8/src/main/java/org/bcit/comp2522/dui/client/Menu.java#L12

**Comment by Jaskarant9899** [comment]
Menu class broken down to different classes for selection pages and difficulty.
