### ISSUE TITLE
Make variable(s) private inside Player

### ISSUE THREAD

**Issue by Qct0411** [COMP2522/project-dui-infinite#74]
https://github.com/COMP2522/project-dui-infinite/blob/a5410a7d7c770a9f37d387359f150561253d73d8/src/main/java/org/bcit/comp2522/dui/client/Player.java#L19
https://github.com/COMP2522/project-dui-infinite/blob/a5410a7d7c770a9f37d387359f150561253d73d8/src/main/java/org/bcit/comp2522/dui/client/Player.java#L18
https://github.com/COMP2522/project-dui-infinite/blob/a5410a7d7c770a9f37d387359f150561253d73d8/src/main/java/org/bcit/comp2522/dui/client/Player.java#L20

**Comment by erictatchell** [comment]
fixed, thank you for the feedback
